# Generated by Django 3.1.3 on 2020-11-28 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60)),
                ('area', models.IntegerField()),
                ('garage', models.BooleanField()),
                ('other', models.JSONField()),
                ('rooms', models.IntegerField()),
                ('geom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asset_registry.geoposition')),
            ],
        ),
    ]
