# Generated by Django 3.1.3 on 2020-11-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_registry', '0002_auto_20201128_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='garage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='other',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
