# Generated by Django 3.1.3 on 2020-11-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_registry', '0003_auto_20201128_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoposition',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='geoposition',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
