jobs:
  build:
    machine:
      image: circleci/classic:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: create .env file
          command: |
            touch .env
            echo DEBUG=on >> .env
            echo SECRET_KEY=test >> .env
            echo PORT=8000 >> .env
            echo DATABASE_NAME=postgres >> .env
            echo DATABASE_USER=postgres >> .env
            echo DATABASE_PASSWORD=postgres >> .env
            echo DATABASE_HOST=db >> .env
            echo DATABASE_PORT=5432 >> .env

      - run:
          name: build containers
          command: |
            docker-compose up --build -d

      - run:
          name: make asset_registry migrations
          command: |
            docker-compose run web python manage.py makemigrations asset_registry

      - run:
          name: migrate
          command: |
            docker-compose run web python manage.py migrate

      - run:
          name: run tests
          command: |
            docker-compose run web python manage.py test