jobs:
  build:
    machine:
      image: circleci/classic:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: create .env file
          command: |
            touch .env
            echo $DEBUG >> .env
            echo $SECRET_KEY >> .env
            echo $PORT >> .env
            echo $DATABASE_NAME >> .env
            echo $DATABASE_USER >> .env
            echo $DATABASE_PASSWORD >> .env
            echo $DATABASE_HOST >> .env
            echo $DATABASE_PORT >> .env

      - run:
          name: build containers
          command: |
            docker-compose up --build -d

      - run:
          name: make asset_registry migrations
          command: |
            docker-compose run web python manage.py makemigrations asset_registry

      - run:
          name: migrate
          command: |
            docker-compose run web python manage.py migrate

      - run:
          name: run tests
          command: |
            docker-compose run web python manage.py test