jobs:
  build:
    machine:
      image: circleci/classic:latest

    working_directory: ~/repo

    environment:
      DEBUG: on
      SECRET_KEY: test
      PORT: 8000
      DATABASE_NAME: test
      DATABASE_USER: test
      DATABASE_PASSWORD: test
      DATABASE_HOST: db
      DATABASE_PORT: 5432

    steps:
      - checkout

      - run:
          name: create empty .env file
          command: |
            touch .env

      - run:
          name: build containers
          command: |
            docker-compose up --build -d

      - run:
          name: make asset_registry migrations
          command: |
            docker-compose run web python manage.py makemigrations asset_registry

      - run:
          name: migrate
          command: |
            docker-compose run web python manage.py migrate

      - run:
          name: run tests
          command: |
            docker-compose run web python manage.py test