jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: build containers
          command: |
            docker-compose up --build -d

      - run:
          name: run tests
          command: |
            docker-compose run web python manage.py test