jobs:
  build:
    machine:
      image: circleci/classic:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: create .env file
          command: |
            touch .env
            echo DEBUG=$DEBUG >> .env
            echo SECRET_KEY=$SECRET_KEY >> .env
            echo PORT=$PORT >> .env
            echo POSTGRES_DB=$POSTGRES_DB >> .env
            echo POSTGRES_USER=$POSTGRES_USER >> .env
            echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env
            echo DATABASE_HOST=$DATABASE_HOST >> .env
            echo DATABASE_PORT=$DATABASE_PORT >> .env
            echo COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN >> .env

      - run:
          name: build containers
          command: |
            docker-compose up --build -d

      - run:
          name: make asset_registry migrations
          command: |
            docker-compose run web python manage.py makemigrations asset_registry

      - run:
          name: migrate
          command: |
            docker-compose run web python manage.py migrate

      - run:
          name: run tests with coverage and send results to coveralls.io
          command: |
            docker-compose run web coverage run --source='.' manage.py test
            docker-compose run web coverage report
            docker-compose run web coverage html
            docker-compose run web coveralls

      - store_artifacts:
          path: htmlcov